name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        uses: android-actions/setup-android@v2

      - name: Instalar NDK
        run: sdkmanager "ndk;25.2.9519653"

      - name: Compilar APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Enviar APK para artefato
        uses: actions/upload-artifact@v4
        with:
          name: JogoAventura-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
